export const SET_LOAD = 'SET_LOAD';
export const SET_ERROR = 'SET_ERROR';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';